extends RefCounted

const BossTuning := preload("res://scripts/boss/boss_tuning.gd")

const VIEW_SIZE := Vector2(540, 960)
const ARENA := Rect2(Vector2(34, 140), Vector2(472, 620))
const MAX_ROOMS := 8
const DEBUG_START_ROOM := 1
const PLAYER_RADIUS := 18.0
const ENEMY_RADIUS := 19.0
const ARROW_RADIUS := 6.0
const PICKUP_RADIUS := 12.0
const GATE_RADIUS := 38.0
const JOYSTICK_CENTER := Vector2(104, 818)
const JOYSTICK_RADIUS := 58.0
const JOYSTICK_KNOB_RADIUS := 24.0
const JOYSTICK_TOUCH_ZONE := Rect2(Vector2(0, 610), Vector2(540, 350))

const SPITTER_ACTIVE_RANGE := 520.0
const SPITTER_RETREAT_DISTANCE := 220.0
const SPITTER_RETREAT_SPEED_SCALE := 0.7
const SPITTER_SHOOT_COOLDOWN_MIN := 1.25
const SPITTER_SHOOT_COOLDOWN_MAX := 1.9

const BOSS_ACTIVE_RANGE := 620.0
const BOSS_RETREAT_DISTANCE := 300.0
const BOSS_APPROACH_DISTANCE := 420.0
const BOSS_RETREAT_SPEED_SCALE := 0.35
const BOSS_PHASE_TWO_RATIO := BossTuning.PHASE_TWO_RATIO
const BOSS_PHASE_THREE_RATIO := BossTuning.PHASE_THREE_RATIO
const BOSS_SPREAD_COUNT := BossTuning.PHASE_ONE_SPREAD_COUNT
const BOSS_SPREAD_ANGLE := BossTuning.PHASE_ONE_SPREAD_ANGLE
const BOSS_SHOOT_COOLDOWN_MIN := BossTuning.PHASE_ONE_COOLDOWN_MIN
const BOSS_SHOOT_COOLDOWN_MAX := BossTuning.PHASE_ONE_COOLDOWN_MAX
const BOSS_PHASE_TWO_SPREAD_COUNT := BossTuning.PHASE_TWO_SPREAD_COUNT
const BOSS_PHASE_TWO_SPREAD_ANGLE := BossTuning.PHASE_TWO_SPREAD_ANGLE
const BOSS_PHASE_TWO_SHOOT_COOLDOWN_MIN := BossTuning.PHASE_TWO_COOLDOWN_MIN
const BOSS_PHASE_TWO_SHOOT_COOLDOWN_MAX := BossTuning.PHASE_TWO_COOLDOWN_MAX
const BOSS_PHASE_THREE_SPREAD_COUNT := BossTuning.PHASE_THREE_SPREAD_COUNT
const BOSS_PHASE_THREE_SPREAD_ANGLE := BossTuning.PHASE_THREE_SPREAD_ANGLE
const BOSS_PHASE_THREE_SHOOT_COOLDOWN_MIN := BossTuning.PHASE_THREE_COOLDOWN_MIN
const BOSS_PHASE_THREE_SHOOT_COOLDOWN_MAX := BossTuning.PHASE_THREE_COOLDOWN_MAX
